name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.x
      - name: Install dependencies
        run: npm ci
      - name: Bundle
        run: npm run bundle
