name: Release

on:
  release:
    types: [published]

jobs:
  publish-to-marketplace:
    name: Publish to Marketplace
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.x
      - name: Install dependencies
        run: npm ci
      - name: Bundle
        run: npm run bundle
      - name: Publish to Marketplace
        run: npm run publish-to-marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
