name: Release

on:
  release:
    types: [published]

jobs:
  bundle-and-publish:
    name: Bundle & Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.x
      - name: Install dependencies
        run: npm ci
      - name: Bundle & Publish
        run: npm run bundle-and-publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
